fortnite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.contrib.staticfiles.urls import static

from fortniteApp.views import BlogView, FortniteView

urlpatterns = [
    url(r'^$', FortniteView.as_view(), name='index'),
    path('fortnite/', include('fortniteApp.urls')),
    url(r'admin/', admin.site.urls),
    url(r'^mainbl/', include('zinnia.urls')),
    url(r'^comments/', include('django_comments.urls')),
]
# + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fortniteApp/urls.py
from django.conf.urls import url

from fortniteApp.views import *
from . import views

app_name = 'fortniteApp'
urlpatterns = [
    url('cosmetics/$', CosmeticsView.as_view(), name='cometics'),
    url('blog/$', BlogView.as_view(), name='blog'),
    url('weapons/$', WeaponsView.as_view(), name='weapons'),
    url('weapon_specifications/(?P<weapon_id>\d+)/$', WeaponSpecificationsView.as_view(), name='weapon_specifications'),
    url('homeblog/(?P<blog_id>\d+)/$', HomeBlogView.as_view(), name='home_blog'),
    url('media', MediaView.as_view(), name='media'),
    url('map', views.map_view, name='map'),
]

fortniteApp/models.py
from django.db import models

RARITY_CHOICES = (
    ('COMMON','Common'),
    ('UNCOMMON', 'Uncommon'),
    ('RARE','Rare'),
    ('EPIC','Epic'),
    ('LEGENDARY','Legendary'),
)

class CosmeticCategory(models.Model):
    category_name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.category_name


class Cosmetics(models.Model):
    cosmetic_category = models.ForeignKey(CosmeticCategory, on_delete=models.CASCADE,
                                        related_name='cosmetic_category_related_name')
    title = models.CharField(max_length=100)
    type = models.CharField(max_length=20,default='type')
    rarity = models.CharField(max_length=9, choices=RARITY_CHOICES, default='EPIC')
    obtained = models.CharField(max_length=5000,default='obtained')
    # decsription = models.CharField(max_length=500)
    image = models.ImageField(upload_to='cosmetics_images')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class CosmeticsPrimaryBanner(models.Model):
    title = models.CharField(max_length=200)
    type = models.CharField(max_length=20,default='type')
    rarity = models.CharField(max_length=9,choices=RARITY_CHOICES, default='grey')
    obtained = models.CharField(max_length=20,default='abc')
    image = models.ImageField(upload_to='cosmetics_banners')
    description = models.CharField(max_length=250)
    expiry_date = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class CosmeticSecondaryBanner(models.Model):
    title = models.CharField(max_length=100)
    type = models.CharField(max_length=20,default='abc')
    rarity = models.CharField(max_length=9, choices=RARITY_CHOICES, default='grey')
    obtained = models.CharField(max_length=20,default='abc')
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='cosmetics_banners')
    expiry_date = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class WeaponCategory(models.Model):
    category_name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.category_name


class Weapons(models.Model):
    weapon_category = models.ForeignKey(WeaponCategory, on_delete=models.CASCADE, related_name='weapons_category_related_name')
    title = models.CharField(max_length=50)
    decsription = models.CharField(max_length=500)
    image = models.ImageField(upload_to='weapon_images')
    release_date = models.DateField()
    bullets_used = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class WeaponSpecifications(models.Model):
    weapon_id = models.ForeignKey(Weapons, on_delete=models.CASCADE, related_name='weapons_related_name')
    # 1 for grey, 2 for green, 3 for blue, 4 for purple, 5 for gold
    weapon_rarity_type = models.IntegerField()
    dps = models.CharField(max_length=10,default='N/A')
    damage = models.CharField(max_length=10,default='N/A')
    env_damage =  models.CharField(max_length=10,default='N/A')
    fire_rate = models.CharField(max_length=10,default='N/A')
    magazine = models.CharField(max_length=10,default='N/A')
    reload_time = models.CharField(max_length=20,default='N/A')
    body_shoot = models.CharField(max_length=10,default='N/A')
    head_shoot = models.CharField(max_length=10,default='N/A')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.weapon_id.title


class WeaponsBanner(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='weapon_banners')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class WeaponsSpecificationsBanner(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='weapon_banners')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class HomePageBanner(models.Model):
    image = models.ImageField(upload_to='homepage_banner')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Media(models.Model):
    title = models.CharField(max_length=100)
    decsription = models.CharField(max_length=500)
    type = models.CharField(max_length=20, default='type')
    image = models.ImageField(upload_to='media_images', null=True, blank=True)
    video = models.FileField(upload_to='media_videos', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class MapCoordinates(models.Model):
    x_coordinate = models.CharField(max_length=100)
    y_coordinate = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    icon_code = models.IntegerField(default=0)


class MainPageBlog(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=100)
    image = models.ImageField(upload_to='home_blogs')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class MediaPageBanner(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='media_banners')
    description = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class MapImage(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)
    image = models.ImageField(upload_to='map_images')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

fortniteApp/views.py
import json

from django.contrib import messages
from django.forms import forms
from django.http import HttpResponse
from django.shortcuts import render
import requests
from django.template import loader
from django.views import View
from django.views.generic import TemplateView, RedirectView, CreateView
from psycopg2.extensions import JSON
from zinnia.models import Entry
import datetime
from datetime import timedelta
from django.views.decorators.csrf import csrf_exempt

from fortniteApp.models import *

ICON_MAP = {
    "pin": 0,
    "loot": 1,
    "machines": 2,
    "shopping": 3,
    "ammo": 4
    }


class FortniteView(TemplateView):
    template_name = 'fortniteData.html'

    def get(self, request, *args, **kwargs):
        user = {}
        entree = ''
        home_banner = ''
        if HomePageBanner.objects.filter():
            home_banner = HomePageBanner.objects.filter().order_by('-id')[0]

        if 'username' in request.GET:

            if 'platform' in request.GET:
                platform = request.GET['platform']
                username = request.GET['username']
                headers = {
                    'authorization': 'a54432b15b52e4c14e2ac8d32994bca7',
                }
                url = 'https://fortniteapi.com/api/getUserID'
                data = {
                    "username": username
                }
                response = requests.post(url,headers=headers, data=data)

                if response.status_code == 200:
                    user = response.json()
                    if 'error' in user:
                        if user['error'] == True:
                            entree = MainPageBlog.objects.filter().order_by('-id')[0]
                            validation_error = "This user does not exist or didn't play fortnite"
                            return render(request, 'fortniteData.html',
                                          {'user': user, 'entree': entree, 'home_banner': home_banner,
                                           'validation_error': validation_error})

                    else:
                        user_id = user['uid']
                        next_url = 'https://fortniteapi.com/api/playerData'
                        new_data = {
                            "user_id": user_id,
                            "platform": platform,
                            "window": "alltime"
                        }
                        new_response = requests.post(next_url, headers=headers, data=new_data)

                        if new_response.status_code == 200:
                            user_profile = new_response.json()
                            return render(request, 'user-details.html', {'data': user_profile})
            else:
                entree = MainPageBlog.objects.filter().order_by('-id')[0]
                validation_error = "Please chose the platform first"
                return render(request, 'fortniteData.html',
                              {'user': user, 'entree': entree, 'home_banner': home_banner, 'validation_error': validation_error})
        else:
            entree = MainPageBlog.objects.filter().order_by('-id')[0]
        return render(request, 'fortniteData.html', {'user': user, 'entree': entree, 'home_banner': home_banner})


class BlogView(TemplateView):
    template_name = "blog.html"

    def get(self, request, *args, **kwargs):
        entries = Entry.objects.all()
        return render(request, self.template_name, {'entries': entries})


class CosmeticsView(TemplateView):
    template_name = 'cosmetics.html'

    def get(self, request, *args, **kwargs):
        cosmetics_results = Cosmetics.objects.all()
        primary_banner = CosmeticsPrimaryBanner.objects.filter(expiry_date__gt=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
        secondary_banner = CosmeticSecondaryBanner.objects.filter(expiry_date__gt=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
        cosmetic_category = CosmeticCategory.objects.all()
        args = {'cosmetics': cosmetics_results, 'banners': primary_banner, 'secondaryBanner': secondary_banner, 'cosmetic_category':cosmetic_category}

        return render(request, self.template_name, args)


class WeaponsView(TemplateView):
    template_name = 'weapons.html'

    def get(self, request, *args, **kwargs):
        weapons_results = Weapons.objects.all()
        weapon_banner = ''
        if WeaponsBanner.objects.filter():
            weapon_banner = WeaponsBanner.objects.filter().order_by('-id')[0]
        weapon_category = WeaponCategory.objects.all()

        args = {'weapons': weapons_results , 'weapon_banner': weapon_banner, 'weapon_categories': weapon_category}
        return render(request, self.template_name, args)


class WeaponSpecificationsView(TemplateView):
    template_name = 'weapon_specifications.html'

    def get(self, request, *args, **kwargs):
        selected_weapon = self.kwargs['weapon_id']
        weapon_specs_object = WeaponSpecifications.objects.filter(weapon_id=selected_weapon).order_by('weapon_rarity_type')
        weapon_specs_new_object = WeaponSpecifications.objects.filter(weapon_id=selected_weapon,dps="N/A",damage="N/A",env_damage="N/A",fire_rate="N/A",magazine="N/A",reload_time="N/A",body_shoot="N/A",head_shoot="N/A")
        weapon_object = Weapons.objects.get(id=selected_weapon)
        weapon_specification_banner = WeaponsSpecificationsBanner.objects.get()
        args = {'weapon_details': weapon_specs_object , 'weapon':weapon_object, 'specs_banner':weapon_specification_banner, 'new_object': weapon_specs_new_object}
        return render(request, self.template_name, args)


class HomeBlogView(TemplateView):
    template_name = 'home_blog.html'

    def get(self, request, *args, **kwargs):
        blog_id = self.kwargs['blog_id']
        home_blog_object = MainPageBlog.objects.get(id=blog_id)
        args = {'home_blog': home_blog_object}
        return render(request, self.template_name,args)


class MediaView(TemplateView):
    template_name = 'media_page.html'

    def get(self, request, *args, **kwargs):
        media_results = Media.objects.all()
        # media_banner = MediaPageBanner.objects.filter(
        #     expiry_date__gt=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
        media_banner = MediaPageBanner.objects.filter()

        args = {'medias': media_results, 'banners': media_banner}

        return render(request, self.template_name, args)

@csrf_exempt
def map_view(request):
    template_name = 'map.html'
    if request.method == 'POST':
        if 'remove' in request.POST:
            pin = MapCoordinates.objects.get(id=int(request.POST['marker_id']))
            pin.delete()
        else:
            map_coordinates = MapCoordinates()
            map_coordinates.x_coordinate = request.POST['x_cord']
            map_coordinates.y_coordinate = request.POST['y_cord']
            if 'icon_name' in request.POST:
                map_coordinates.icon_code = ICON_MAP.get(request.POST['icon_name'])

            map_coordinates.save()

    all_marked_locations = MapCoordinates.objects.filter()
    map_pins =[]
    for foo in all_marked_locations:
        pin_info = {}
        pin_info['id']=foo.id
        pin_info['title']='map pin ' + str(foo.id)
        pin_info['xcoord']=foo.x_coordinate
        pin_info['ycoord']=foo.y_coordinate
        pin_info['icon_code'] = foo.icon_code
        map_pins.append(pin_info)
    map_image = MapImage.objects.filter().order_by('-id')[0]
    args = {'marked_locations': map_pins, 'map_image': map_image}
    return render(request,template_name, args)

fortniteApp/templates/blog.html
<head>
  <title>Updates</title>
    <meta name="keywords" content="fortnite, blog, fortnitego">
    <meta name="description" content="fortnite blog">
</head>
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="p-t-35 custom_blog_set">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-10 col-lg-8 mx-auto">

            {% for entry in entries %}
                <div class="post">
                    <div class="custom_blog_set_finale">
                        <h2 class="post-title"><a href="{{ entry.short_url }}">{{ entry.title }}</a></h2>
                        <div class="post-meta">
                          <span><i class="fa fa-clock-o"></i>Published Date: {{ entry.publication_date }}</span>
                        </div>
                    </div>
                    <div class="post-thumbnail">
                      {% if entry.image %}
                        <img style="" src="{{ entry.image.url }}" alt="{{ entry.lead }}">
                      {% else %}
                          <h5 style="font-style: italic;">No Image Attached in Blog</h5>
                      {% endif %}
                    </div>
                <div class="blog_homepage">
                    <p class="blog_p_set_homepage">{{ entry.content }}</p>
                </div>
              </div>
            {% endfor %}

        </div>
      </div>
    </div>
  </section>
  {% endblock %}

{% block js %}
    <script src="{% static 'plugins/jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'plugins/popper/popper.min.js'%}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>

    <script src="{% static 'plugins/owl-carousel/js/owl.carousel.min.js' %}"></script>
    <script>
        (function($) {
            "use strict";
            // owl carousel
          $('.owl-posts').owlCarousel({
            margin: 5,
            loop: true,
            dots: false,
            autoplay: true,
            responsive: {
              0: {
                items: 1
              },
              1024: {
                items: 1,
                center: false
              },
              1200: {
                items: 2,
                center: true
              }
            }
          });

      $('.owl-videos').owlCarousel({
        margin: 15,
        loop: true,
        dots: false,
        responsive: {
          0: {
            items: 1
          },
          700: {
            items: 2
          },
          800: {
            items: 3
          },
          1000: {
            items: 4
          },
          1200: {
            items: 6
          }
        }
      });
    })(jQuery);
  </script>

  <!-- theme js -->
  <script src="{% static 'js/theme.min.js' %}"></script>
{% endblock %}

fortniteApp/templates/fortniteData.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="bg-inverse p-y-0 main-home-inverse-section-custom">
    <div class="owl-carousel owl-slide full-height">
      <div class="carousel-item" style="background-image: url('{{ home_banner.image.url }}');">
        <div class="carousel-overlay"></div>
        <div class="carousel-caption">
              <div class="main-home-page-style crowsal-form-custom">
                  <h3 style="color: white">Fortnite Stats</h3>
                  <form method="get">

                      <div class="main-home-custom-css">
                          <div class="console-selection">

                            <label class="layersMenu consoles-style">
                                <input type="radio" name="platform" value="xb1" />
                                <i class="fab fa-xbox newclass"></i>
                            </label>

                              <label class="layersMenu consoles-style">
                                <input type="radio" name="platform" value="ps4" />
                                <i class="fab fa-playstation newclass"></i>
                            </label>

                            <label class="layersMenu consoles-style">
                                <input type="radio" name="platform" value="pc" />
                                <i class="fab fa-windows newclass"></i>
                            </label>
                          </div>
                          <div class="username-selection">
                              <input type="text" name="username" class="form-control username-textbox-custom" placeholder="Username" required>
                          </div>
                          <div class="submit-btn-custom">
                              <button type="submit">Go</button>
                          </div>
                      </div>
                  </form>
                  <div style="text-align: center">
                      {% if validation_error %}
                                <h4 style="color: red; margin-left: 70px;">{{ validation_error }}</h4>
                      {% endif %}
                  </div>
                  <div class="arrow bounce">
                      <a class="fa fa-arrow-down fa-2x" id="arrow_down" href="#scroll"></a>
                  </div>
              </div>
        </div>
      </div>
    </div>
  </section>
    <section class="p-t-35 custom_blog_set" id="scroll">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-10 col-lg-8 mx-auto">

                <div class="post">
                    <div class="custom_blog_set_finale">
                        <h2 class="post-title"><a href="{% url 'fortniteApp:home_blog' blog_id=entree.id %}">{{ entree.title }}</a></h2>
                        <div class="post-meta">
                          <span><i class="fa fa-clock-o"></i>Published Date: {{ entree.created_at }}</span>
                        </div>
                    </div>
                    <div class="post-thumbnail">
                      {% if entree.image %}
                        <img style="" src="{{ entree.image.url }}" alt="{{ entree.title }}">
                      {% else %}
                          <h5 style="font-style: italic;">No Image Attached in Blog</h5>
                      {% endif %}
                    </div>
                <div class="blog_homepage">
                    <p class="blog_p_set_homepage">{{ entree.description }}</p>
                </div>
              </div>

        </div>
      </div>
    </div>
  </section>

  {% endblock %}

fortniteApp/templates/getData.html
{#{% extends 'base.html' %}#}

{% block content %}
  <h2>GEO API</h2>
  <p>Your ip address is <strong>{{ ip }}</strong>, and you are probably in <strong>{{ country }}</strong> right now.</p>
{% endblock %}

fortniteApp/templates/home_blog.html
<head>
  <title>Home-Blog</title>
    <meta name="fortnite blog" content="Fortnite Go Home-Blog">
</head>
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="p-t-35 custom_blog_set">
    <div class="container">
      <div class="row">
          <div class="col-lg-1"></div>
        <div class="col-lg-10">
                <div class="post post-single">
                    <h2 class="post-title"><a href="#">{{ home_blog.title }}</a></h2>
                    <div class="post-meta">
                      <span><i class="fa fa-clock-o"></i>Published Date: {{ home_blog.updated_at }}</span>
                    </div>
                    <div class="post-thumbnail">
                      {% if home_blog.image %}
                        <img style="" src="{{ home_blog.image.url }}">
                      {% else %}
                          <h5 style="font-style: italic;">No Image Attached in Blog</h5>
                      {% endif %}
                    </div>
                <div class="blog_homepage">
                    <p class="blog_p_set_homepage">{{ home_blog.description }}</p>
                </div>
              </div>

        </div>
      </div>
    </div>
  </section>
    <div class="blog_comment_custom_set">
    <section class="p-t-30 weapon_specs_custom_set">
        <div class="container">
          <div class="row">
            <div class="col-lg-10 customeee">
            <div id="disqus_thread"></div>
                <script>
                    (function() { // DON'T EDIT BELOW THIS LINE
                    var d = document, s = d.createElement('script');
                    s.src = 'https://fortnitego-com.disqus.com/embed.js';
                    s.setAttribute('data-timestamp', +new Date());
                    (d.head || d.body).appendChild(s);
                    })();
                </script>
            </div>
          </div>
        </div>
    </section>
</div>
  {% endblock %}

{% block js %}
    <script src="{% static 'plugins/jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'plugins/popper/popper.min.js'%}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>

    <script src="{% static 'plugins/owl-carousel/js/owl.carousel.min.js' %}"></script>
    <script>
        (function($) {
            "use strict";
            // owl carousel
          $('.owl-posts').owlCarousel({
            margin: 5,
            loop: true,
            dots: false,
            autoplay: true,
            responsive: {
              0: {
                items: 1
              },
              1024: {
                items: 1,
                center: false
              },
              1200: {
                items: 2,
                center: true
              }
            }
          });

      $('.owl-videos').owlCarousel({
        margin: 15,
        loop: true,
        dots: false,
        responsive: {
          0: {
            items: 1
          },
          700: {
            items: 2
          },
          800: {
            items: 3
          },
          1000: {
            items: 4
          },
          1200: {
            items: 6
          }
        }
      });
    })(jQuery);
  </script>

  <!-- theme js -->
  <script src="{% static 'js/theme.min.js' %}"></script>
{% endblock %}

fortniteApp/templates/weapons.html
<head>
  <title>Weapons</title>
    <meta name="keywords" content="fortnite, weapons, fortnitego">
    <meta name="description" content="fortnite weapons">
</head>
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <section class="hero hero-game" style="background-image: url('{{ weapon_banner.image.url }}');">
    <div class="overlay"></div>
    <div class="container">
      <div class="hero-block">
        <div class="hero-left">
          <h2 class="hero-title">{{ weapon_banner.title }}</h2>
          <p>{{ weapon_banner.description }}</p>
        </div>
      </div>
    </div>
  </section>

  <section class="p-t-30">
    <div class="container">

    <section class="toolbar toolbar-links">
          <ul class="toolbar-nav hidden-md-down m-r-25 nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#home">All</a></li>
                {% for category in weapon_categories %}
                    <li><a data-toggle="tab" href="#{{ category.category_name|cut:" " }}">{{ category.category_name }}</a></li>
                {% endfor %}
          </ul>
    </section>

     <div class="tab-content">
        <div id="home" class="tab-pane fade in active show">
          <h3>All</h3>

            <div class="row">
              {% if weapons %}
                  {%  for weapon in weapons %}
                      <div class="col-12 col-sm-6 col-md-4">
                          <div class="card card-lg">
                            <div class="card-img card-main-div-set" style="border-left: 1px solid #E3E0E0; border-top: 1px solid #E3E0E0; border-right: 1px solid #E3E0E0;">
                              <a href="{% url 'fortniteApp:weapon_specifications' weapon_id=weapon.id %}">
                              <img src="{{ weapon.image.url }}" class="card-img-top weapons_size_custom_set" style="">
                            </a>
                            </div>
                            <div class="card-block">
                              <h4 class="card-title">
                                <a href="{% url 'fortniteApp:weapon_specifications' weapon_id=weapon.id %}">{{ weapon.title }}</a>
                              </h4>
                              <p class="card-text">{{ weapon.decsription }}</p>
                            </div>
                          </div>
                        </div>
                  {% endfor %}
                  {% else %}
                    <h4>No weapon found</h4>
              {% endif %}
          </div>

    </div>
  {% if weapon_categories %}
      {% for wc in weapon_categories %}
        <div id="{{ wc.category_name|cut:" "}}" class="tab-pane fade">
          <h3>{{ wc.category_name }}</h3>
          <div class="row">
            {% for foo in wc.weapons_category_related_name.all %}
                  <div class="col-12 col-sm-6 col-md-4">
                  <div class="card card-lg">
                    <div class="card-img card-main-div-set">
                      <a href="{% url 'fortniteApp:weapon_specifications' weapon_id=foo.id %}">
                      <img src="{{ foo.image.url }}" class="card-img-top weapons_size_custom_set" style="">
                    </a>
                    </div>
                    <div class="card-block">
                      <h4 class="card-title">
                        <a href="{% url 'fortniteApp:weapon_specifications' weapon_id=foo.id %}">{{ foo.title }}</a>
                      </h4>
                      <p class="card-text">{{ foo.decsription }}</p>
                    </div>
                  </div>
                </div>
              {% endfor %}
          </div>
        </div>
     {% endfor %}
     {% endif %}
  </div>

    </div>
  </section>
{% endblock %}
{% block js %}
  <script src="{% static 'plugins/jquery/jquery-3.2.1.min.js'%}"></script>
  <script src="{% static 'plugins/popper/popper.min.js'%}"></script>
  <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js'%}"></script>

  <!-- plugins js -->
  <script src="{% static 'plugins/easypiechart/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'plugins/easypiechart/jquery.easypiechart.min.js' %}"></script>
  <script>
    (function($) {
      "use strict";
      // easyPieChart
      $('.chart').easyPieChart({
        barColor: '#5eb404',
        trackColor: '#e3e3e3',
        easing: 'easeOutBounce',
        onStep: function(from, to, percent) {
          $(this.el).find('span').text(Math.round(percent));
        }
      });
      $('.search-game, .navbar-search .form-control').keyup(function() {
        var search = $(this).val().toLowerCase();
        $.each($('.card-title'), function() {
          if ($(this).text().toLowerCase().indexOf(search) === -1) {
            $(this).parent().parent().parent().hide();
          } else {
            $(this).parent().parent().parent().show();
          }
        });
      });
    })(jQuery);
  </script>

  <!-- theme js -->
  <script src="{% static 'js/theme.min.js' %}"></script>

{% endblock %}